config/routes.rb
Sx::Application.routes.draw do
  get "contact/index"
  get 'productions/index'
  get 'productions/show'
  get 'productions/edit'
  get 'productions/new'
  get 'productions/change_type'
  root :to => 'home#index'
  resource :register ,:login
  get 'login/index'
  post 'login/login' => 'login#login'
  get 'login/logout'
  get 'register/index'
  post 'register/register' => 'register#register'
  get 'home/index'
  resources :users do
    collection do
      get 'checkname'
    end
  end

end

app/models/production.rb
class Production < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  #validates_uniqueness_of :name
  validates :password,confirmation: true
  #validates :password_confirmation, presence: true
  #validates_format_of :email, with: /\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*/, on: :create
  def self.login(name, password)
    hashed_password = hash_password(password || "")
    find(:first,:conditions => ["name = ? and hashed_password = ?",name, hashed_password])
  end
  def try_to_login
    User.login(self.name, self.password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @current_user = User.find_by(id: session[:user_id])
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
    @user = User.find_by(id: '1')
  end
  def login
    if request.get?
      session[:user_id] = nil
      @user = User.new
    else
  
      logged_in_user = User.find_by(name: params[:name],password: params[:password])
      #logged_in_user = @user.try_to_login

      if logged_in_user
        session[:user_id] = logged_in_user.id
        redirect_to home_index_path
      else
        render login_index_path
        flash[:notice] = 'Invalid user/password combination'
      end
    end
  end
  def logout
    session[:user_id] = nil
    render home_index_path
  end
end

app/controllers/productions_controller.rb
class ProductionsController < ApplicationController

  def index

    unless params[:protype].blank?
      @products=Production.where(pro_type: params[:protype])
    else
      @products = Production.where(pro_type: 'T')
    end
    params[:way_display] = 'pic' if params[:way_display].blank?
  end

  def show
  end

  def edit
  end

  def new
  end

  def change_type
    puts  'it is coming back!'
    type = params[:protype]
    @products = Production.where(pro_type: type)
    #binding.pry
    #redirect_to :action=>'index',:protype =>  params[:protype]
    render :controller => 'Productions',:action => 'index'
  end
end

app/controllers/register_controller.rb
class RegisterController < ApplicationController
  layout "loginregister"
  include RegisterHelper
  def index
  end
  def register
    user = User.new
    user.name = params[:register_form][:name]
    user.password = params[:register_form][:password]
    user.email = params[:register_form][:email]
    user.company = params[:register_form][:company]
    #binding.pry
    valid_flag,error_msg = validate_user_data user
    unless valid_flag
      flash[:notice] = error_msg
      render register_index_path
      return
    end
    if user.save
      session[:user_id] = user.id
      flash[:notice] = 'register success!'
      redirect_to home_index_path
    else
      flash[:notice] = 'register failure!'
      render register_index_path
    end
  end
  def validate_name_unique
      project_templatemy = ProjectTemplate.find_by_id(params[:templatemy_id])
      user = User.find_by(name: params[:name])
      if user.blank?
        render :inline => "<img src='/assert/true.png' />"
      else
        render :inline => "<img src='/assert/false.png' />"
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def checkname
    if User.where(name: params[:name]).count == 0
      render :nothing => true,:status => 200
    else
      render :nothing => true,:status => 409
    end
    return
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/productions_helper.rb
module ProductionsHelper
end

app/helpers/register_helper.rb
module RegisterHelper
  def validate_user_data user
    valid_flag = true
    validate_string = ''
    if User.where(name: user.name).count > 0
      validate_string += "name is exist!\r"
      valid_flag = false
    end
    if user.password.length < 6
      validate_string += "password's length must be greater than 6!\r"
      valid_flag = false
    end
    email_reg = /\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*/
    if user.email.match(email_reg).blank?
      validate_string += "email's format is invalid!\r"
      valid_flag = false
    end
    return valid_flag,validate_string
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contact/index.html.erb
<%= stylesheet_link_tag "content_layout" %>
<%= stylesheet_link_tag "contact" %>
<div id="container">
  <div id="classify">
  </div>
  <div id="how_show">
  </div>
  <div id="content">
    <p>手机:1350695894</p>
    <p>座机:021-52354569</p>
    <p>邮箱:6598545454@qq.com</p>
    <p></p>
  </div>
</div>

app/views/home/index.html.erb
<%= stylesheet_link_tag "home" %>
home
<!--<div id="indexCover" >
  <div id="topBar">
    <% if @current_user.blank? %>
    <ul>
      <li><%= link_to t(:register),register_index_path%></li>
      <li><%= link_to t(:login),login_index_path%></li>
    </ul>
    <% else %>
    <ul>
      <li><%= link_to t(:logout),login_logout_path%></li>
      <li><%= link_to @current_user.name   %></li>
    </ul>
    <% end %>
  </div>
  <div class="prev" data-pre  ></div>
  <div class="next" data-next ></div>
</div>
<div id="blank1"></div>
<div id="funMenu">
  <div id="M1" data-btntype="veg" >
    <%= image_tag('rails.png') %>
  </div>
  <div id="M2" data-btntype="fla" >
    <%= image_tag('rails.png') %>
  </div>
  <div id="M3" data-btntype="oth" >
    <%= image_tag('rails.png') %>
  </div>
</div>
<div id="blank2"></div>
<% 6.times do %>
  <div class="box1">
    <%= image_tag("1.jpg") %>
    <p>
      Lorem ipsum
    </p>
    <br />
    <a href="http://www.designshock.com/"> DesignShock.com </a>
  </div>
  <div class="box1">
    <%= image_tag("2.jpg") %>
    <p>
      Lorem ipsum
    </p>
    <br />
    <a href="http://www.designshock.com/"> DesignShock.com </a>
  </div>
  <div class="box1">
    <%= image_tag("3.jpg") %>
    <p>
      Lorem ipsum
    </p>
    <br />
    <a href="http://www.designshock.com/"> DesignShock.com </a>
  </div>
  <div class="box1">
    <%= image_tag("4.jpg") %>
    <p>
      Lorem ipsum
    </p>
    <br />
    <a href="http://www.designshock.com/"> DesignShock.com </a>
  </div>
<% end %>
-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sx</title>
  <!--%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %-->
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "layout" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="top">
    <div id="show_name">
      <% unless session[:user_id].blank? %>
          <% @current_user = User.find_by(id: session[:user_id]) %>
          <ul>
            <li><%= link_to @current_user.name   %></li>
            <li><%= link_to t(:logout),login_logout_path%></li>
          </ul>
      <% end %>
    </div>
    <div id = "header">
        <div class="col-full">
            <div id="logo" class="f1">
                <a href="http://www.baidu.com">
                  <%= image_tag('lwd-logo-new.png')%>
                </a>
            </div>
            <ul id="nav" class="fr">
                  <li id="menu-item-51" class="">
                    <%= link_to t(:home),home_index_path %>
                  </li>
                  <li id="menu-item-51" class="">
                    <%= link_to t(:product),productions_index_path %>
                  </li>
                  <li id="menu-item-51" class="">
                    <%= link_to t(:contact),contact_index_path %>
                  </li>
                  <li id="menu-item-51" class="">
                    <%= link_to t(:login_register),login_index_path %>
                  </li>
            </ul>
        </div>
    </div>
</div>
<%= yield %>

</body>
</html>

app/views/login/index.html.erb
<%= stylesheet_link_tag "login" %>
<%= stylesheet_link_tag "register" %>
<%=  javascript_include_tag "login" %>
<%= javascript_include_tag "register"%>
<%= stylesheet_link_tag "content_layout" %>
<!---<%= form_for('login_form',url:'/login/login') do |f| %>
   <table>
     <tr>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :password %>
      <%= f.password_field :password %>
     </tr>
     <tr>
       <td></td>
       <td><%= f.submit "login"  %></td>
     </tr>
   </table>
<% end %>
<a href="#" data-background-color = "#990000" data-no-turbolink >Paint it red</a>
<%= debug(@user)%>

<div id="container">
  <div id="content">
    <div class="wrapper">
      <form name="f_0_11_1_3_1" method="post" action="/app/wa/signIn">
        <input type="hidden" value="false" name="returning" id="returning" />
        <table class="login" style="margin-left: auto; margin-right: auto;">
          <tr>
            <td><p class="mtop0 mbottom025"><strong><label for="email"><%= t(:name)%></label></strong></p>
              <input id="email" tabindex="1" class="inputtext" type="text" name="email" /></td>
          </tr>
          <tr>
            <td><p class="mtop05 mbottom025"><strong><label for="password"><%= t(:password)%></label></strong></p>
              <input tabindex="2" class="inputtext" type="password" name="password" id="password" /></td>
          </tr>

          <tr>
            <td>
              <p class="mtop025 mbottom0 smalltxt"><a href="/app/wa/Password/forgot">Forgot password?</a>
                <span style="padding: 0 3px;">|</span> <a href="/app/wa/GoogleApps/signIn">Login using Google Apps</a>
              </p>
            </td>
          </tr>
          <tr>
            <td>
              <p class="mtop025 mbottom0 smalltxt"><input type="checkbox" name="remember" id="rememberMe" tabindex="3"/> <label for="rememberMe">Remember me</label></p>
            </td>
          </tr>
          <tr>
            <td style="padding-top: 10px;">
              <input class="public-button" type="submit" tabindex="4" value="login" />
            </td>
          </tr>
        </table>
      </form>
    </div>
  </div>
</div-->

<div id="container">
  <div id="classify">
  </div>
  <div id="how_show">
  </div>
  <div id="content">
    <div class="login_title"><h1>登陆从这里开始</h1></div>
    <div class="wrapper">
      <%= form_for 'login_form',url:'/login/login' do %>
          <table>
            <tr>
              <td>
               <label for="email"><%= t(:name)%></label>
              </td>
              <td>
                <%= text_field_tag 'name','',class:'txt1_bg' %>
              </td>
            </tr>
            <tr>
              <td>
                <label for="password"><%= t(:password)%></label>
              </td>
              <td>
                <%= password_field_tag 'password','',class:'txt1_bg'%>
              </td>
            </tr>
            <tr>
              <td></td>
              <td>
                <div class="register_button ">
                <%= submit_tag t(:login),class: 'position_login_btn' %>
                </div>
              </td>
            </tr>
          </table>
      <% end %>
    </div>
    <div class="register">
        <div class="register_title"><h1>还没注册，↓</h1></div>
      <%= form_for('register_form',url:'/register/register') do |f| %>
            <div class="content_register">
              <table class="ipt_box">
                <tr>
                  <td>
                    <%= f.label t(:name) %><span class="required"> *</span>
                  </td>
                  <td>
                    <%= f.text_field :name,required: true,class:'txt1_bg','data-validate'=> '/users/checkname' %>
                  </td>
                  <td>
                    <div id="divName_info"></div>
                  </td>
                </tr>
                <tr><td>&nbsp;</td></tr>
                <tr>
                  <td>
                    <%= f.label t(:password) %><span class="required"> *</span>
                  </td>
                  <td>
                    <%= f.password_field :password,required:true,class:'txt1_bg',"data-length" => "" %>
                  </td>
                  <td>
                    <div id='divPassword1_info'></div>
                  </td>
                </tr>
                <tr><td>&nbsp;</td></tr>
                <tr>
                  <td>
                    <%= f.label t(:password_again) %><span class="required"> *</span>
                  </td>
                  <td>
                    <%= f.password_field :password_confirmation,required:true,class:"txt1_bg",'data-confirmation' => '' %>
                  </td>
                  <td>
                    <div id="divPassword2_info"></div>
                  </td>
                </tr>
                <tr><td>&nbsp;</td></tr>
                <tr>
                  <td>
                    <%= f.label t(:mail) %><span class="required"> *</span>
                  </td>
                  <td>
                    <%= f.text_field :email,required:true,class:"txt1_bg",'data-email'=>'' %>
                  </td>
                  <td>
                    <div id="divMail_info"></div>
                  </td>
                </tr>
                <tr><td>&nbsp;</td></tr>
                <tr>
                  <td>
                    <%= f.label t(:company) %>
                  </td>
                  <td>
                    <%= f.text_field :company,class:"txt1_bg" %>
                  </td>
                </tr>
              </table>
              <br/>
              <% if flash[:notice] %>
                  <div class="notice"><%= flash[:notice] %></div>
              <% else %>
                  <br/>
              <% end %><br/>
              <div class="register_button position_button">
                <%= f.submit t(:btn_register)  %>
              </div>
            </div>
      <% end %>
  </div>
</div>

app/views/productions/_production.html.erb
<% if params[:way_display] == 'text'%>
<!--p>Product Name:<%= production.name %></p-->

  <tr>
    <td>
      <%= production.no %>
    </td>
    <td>
      <%= production.name %>
    </td>
    <td>
      <%= production.price %>
    </td>
    <td>
      <%= production.unit %>
    </td>
    <td>
      <%= production.placefrom %>
    </td>
    <td>
      <%= production.available %>
    </td>
  </tr>
<% elsif params[:way_display] == 'pic' %>
    <div class="box1">
      <%= image_tag("li.jpg") %>
      <%= production.name %>
      <br/>
      <!--a href="http://www.designshock.com/"> DesignShock.com </a-->
    </div>
<% end %>

app/views/productions/edit.html.erb
<h1>Productions#edit</h1>
<p>Find me in app/views/productions/edit.html.erb</p>

app/views/productions/index.html.erb
<%= stylesheet_link_tag "productions" %>
<%= stylesheet_link_tag "content_layout" %>
<%= stylesheet_link_tag "ihower" %>
<div id="container">
<div id="classify">
  <div id="choice_title">

  </div>
  <div id="nav">
  <ul id="classify_item">
    <li id="F" class="item">
      <%= label_tag 'vgg','#','data-changetype' => '/productions/change_type','data-protype'=>'V'%>
      <%= link_to t(:V),productions_index_path(:protype => 'V',:way_display => params[:way_display]) %>
    </li>
    <li id="F"  class="item">
      <%= link_to t(:F),productions_index_path(:protype => 'F',:way_display => params[:way_display]) %>
    </li>
    <li id="T"  class="item">
      <%= link_to t(:T),productions_index_path(:protype => 'T',:way_display => params[:way_display]) %>
    </li>
    <li id="D" class="item">
      <%= link_to t(:D),productions_index_path(:protype => 'D',:way_display => params[:way_display]) %>
    </li>
    <li id="R" class="item">
      <%= link_to t(:R),productions_index_path(:protype => 'R',:way_display => params[:way_display]) %>
    </li>
    <li id="O" class="item">
      <%= link_to t(:O),productions_index_path(:protype => 'O',:way_display => params[:way_display]) %>
    </li>
    <li id="L" class="item88">
      <%= link_to t(:L),productions_index_path(:protype => 'L',:way_display => params[:way_display]) %>
    </li>
    <li id="Z" class="item"  data-qita='/productions/index' data-protype="Z" data-way_display=<%=params[:way_display]%>>
      <!--%= link_to t(:Z),productions_index_path(:protype => 'Z',:way_display => params[:way_display]) %-->
      <%= t(:Z)%>
    </li>
  </ul>
  </div>
</div>
<a id="bai"  href="http://www.baidu.com">baidu.com</a>
<div id="how_show">
  <div class="row">
    <div class="col-sm-6">

      <!-- normal -->
      <div class="ih-item circle effect15 left_to_right">
        <% if params[:protype].blank? %>
            <a href=<%= 'index?way_display=text'%>>
        <%else%>
            <a href=<%= 'index?way_display=text'+'&protype='+ params[:protype] %>>
        <%end%>
        <div class="img"><%= image_tag('li.jpg') %></div>
        <div class="info">
          <h3>list show</h3>
          <p></p>
        </div></a></div>
      <!-- end normal -->

    </div>
    <div class="col-sm-6">

      <!-- colored -->
      <div class="ih-item circle colored effect15 left_to_right">
        <% if params[:protype].blank? %>
            <a href=<%= 'index?way_display=pic'%>>
        <%else%>
            <a href=<%= 'index?way_display=pic'+'&protype='+ params[:protype] %>>
        <%end%>
        <div class="img"><%= image_tag('2.jpg') %></div>
        <div class="info">
          <h3>image show</h3>
          <p></p>
        </div></a>
      </div>
      <!-- end colored -->

    </div>
  </div>
</div>
<div id="content">
  <% if params[:way_display] == 'text'%>
      <table>
        <tr>
          <th><%= t(:no)%></th><th><%= t(:name)%></th><th><%= t(:price)%></th><th><%= t(:unit)%></th><th><%= t(:placefrom)%></th><th><%= t(:available)%></th>
        </tr>
      <%= render @products %>
      </table>
  <% elsif params[:way_display] == 'pic' %>
      <%= render @products %>
  <% end %>
</div>
</div>

app/views/productions/new.html.erb
<h1>Productions#new</h1>
<p>Find me in app/views/productions/new.html.erb</p>

app/views/productions/show.html.erb
<h1>Productions#show</h1>
<p>Find me in app/views/productions/show.html.erb</p>

app/views/register/index.html.erb
<%= javascript_include_tag "register"%>

<div class="top_register"></div>
<%= form_for('register_form',url:'/register/register') do |f| %>

<div class="register">
  <div class="logo_register">
    <%= image_tag("logo_login02.gif") %>
  </div>
  <div class="content_register">
  <div class="top_bg"></div>
  <ul class="login_top">
	<li><%=  image_tag("pic_login01.gif")%></li>
	<li><%=  image_tag("pic_login03.gif")%></li>
  </ul>
  <table class="ipt_box">
    <tr>
      <td>
        <%= f.label t(:name) %><span class="required"> *</span>
      </td>
      <td>
        <%= f.text_field :name,required: true,class:'txt1_bg','data-validate'=> '/users/checkname' %>
      </td>
      <td>
        <div id="divName_info"></div>
      </td>
    </tr>
    <tr><td>&nbsp;</td></tr>
    <tr>
      <td>
        <%= f.label t(:password) %><span class="required"> *</span>
      </td>
      <td>
        <%= f.password_field :password,required:true,class:'txt1_bg',"data-length" => "" %>
      </td>
      <td>
        <div id='divPassword1_info'></div>
      </td>
    </tr>
    <tr><td>&nbsp;</td></tr>
    <tr>
      <td>
        <%= f.label t(:password_again) %><span class="required"> *</span>
      </td>
      <td>
        <%= f.password_field :password_confirmation,required:true,class:"txt1_bg",'data-confirmation' => '' %>
      </td>
      <td>
        <div id="divPassword2_info"></div>
      </td>
    </tr>
    <tr><td>&nbsp;</td></tr>
    <tr>
      <td>
        <%= f.label t(:mail) %><span class="required"> *</span>
      </td>
      <td>
        <%= f.text_field :email,required:true,class:"txt1_bg",'data-email'=>'' %>
      </td>
      <td>
        <div id="divMail_info"></div>
      </td>
    </tr>
    <tr><td>&nbsp;</td></tr>
    <tr>
      <td>
        <%= f.label t(:company) %>
      </td>
      <td>
        <%= f.text_field :company,class:"txt1_bg" %>
      </td>
    </tr>
  </table>
  <br/>
  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% else %>
    <br/>
  <% end %><br/>
  <div class="register_button">
	<%= f.submit t(:btn_register)  %>
  </div>
  <div class="btm_bg"></div>
  </div>
<% end %>